name: Java CD with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    
    steps:

    - name: Download artifact from GitHub Packages
      uses: actions/download-artifact@v4
      with:
       name: app
       github-token: ${{ secrets.GITHUB_TOKEN }}
       path: downloaded_artifact
       run-id: 11
