name: Java CD with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    
    steps:

    - name: Download artifact from GitHub Packages
      uses: actions/download-artifact@v2
      with:
        name: app
        path: downloaded_artifact

    - name: Deploy WAR file to Tomcat webapps directory
      run: sudo cp downloaded_artifact/app.war /var/lib/tomcat9/webapps/

    - name: Restart Tomcat if needed
      run: sudo systemctl restart tomcat9.service
