name: Java CD with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - name: Echo GitHub Token
      run: echo ${{ secrets.GITHUB_TOKEN }}

    - name: Download artifact from GitHub Packages
      uses: actions/download-artifact@v3
      with:
        name: app
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        repository: Diwakarpersonal/spring3hibernate
        path: downloaded_artifact
        run-id: 8573707252
